### ISSUE TITLE
is't possible to substitute the embedding instance segmentation with mask-rcnn

### ISSUE THREAD

**Issue by blueardour** [svip-lab/PlanarReconstruction#19]
Hi, Dear authors,

I'm reading and trying to recover this excellent work. For the segmentation branch, based on my previous limited understanding, embedding style segmentation might be less accurate that the mask-rcnn ones. And also the kmeans cluster step is less computing efficient on GPUs for both training and inference. Thus, I wonder does the framework work if replacing the embedding instance segmentation branch with mask-rcnn?

**Comment by bertjiazheng** [comment]
Yes, there are two main approaches to instance segmentation: proposal-based (e.g., Mask RCNN) and proposal-free (e.g., embedding-based). There is a trade-off between segmentation accuracy and speed. The speed is also an important aspect in real-time applications. Further, we use mean-shift instead of k-means clustering. 

If you try to work on detection-based method, you can refer to the concurrent work [PlaneRCNN](https://github.com/NVlabs/planercnn). 

Best,
Jia

**Comment by blueardour** [comment]
Hi, @bertjiazheng  Thanks for the comment.

My final purpose is to deploy the planar sementation on smart cellphones. I ever looked into the PlaneRCNN repo, the code seemed to be more complex that this one. I prefer this repo as the framework is clean and simple. The trouble for me is the mean shift part for its risking of long exection time on ARM cpus. Thus, I'm considering to replace the embedding style segmentation to proposal one (ARM computing library seems to provide the support of Mask RCNN or NMS already).

Whatever, with no respect to deployment on specific platforms currently, do you think it's promising to obtain the same accuracy (or even better) if substituting embedding segmentation with region proposal one?

**Comment by bertjiazheng** [comment]
We do not have a quantitive comparison with PlaneRCNN since the data is slightly different. But in semantic instance segmentation, the proposal-free methods fail to perform as well as detection-based methods like Mask RCNN.

**Comment by blueardour** [comment]
@bertjiazheng   Very thanks for the opinion.
